//go:build ignore

// gen.go generates sdk.go by reflecting on internal package exports.
//
// Run: go generate ./sdk/
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"os"
	"slices"

	"golang.org/x/tools/go/packages"
)

const module = "github.com/Chocapikk/pik"

// pkgSpec defines which symbols to re-export from an internal package.
type pkgSpec struct {
	path    string            // import path relative to module root
	alias   string            // import alias ("" = default, e.g. "pikhttp")
	include []string          // selective: only these symbols (nil = all exported)
	renames map[string]string // original -> sdk name (only for collisions)
	skip    []string          // symbols to skip even if exported
}

var specs = []pkgSpec{
	{
		path: "pkg/core",
		// All exports except Register wrappers and internal helpers.
		skip: []string{"Register", "RegisterFrom", "HasOpt"},
	},
	{
		path:    "pkg/log",
		include: []string{"Status", "Success", "Error", "Warning", "Verbose", "Debug"},
	},
	{
		path:    "pkg/output",
		include: []string{"Banner", "Print", "Println", "Spinner"},
	},
	{
		path: "pkg/payload",
		include: []string{
			// Reverse shell generators
			"Bash", "BashMin", "BashFD", "Python", "PythonPTY",
			"Perl", "Ruby", "PHP", "Netcat", "NetcatMkfifo",
			"PowerShell", "Socat", "NodeJS", "Awk", "Lua", "Java",
			// Stager generators
			"Curl", "Wget", "CurlPipe", "WgetPipe",
			"PHPDownload", "PerlDownload", "PythonDownload",
			"PowerShellDownload", "PowerShellIEX",
			"Certutil", "Bitsadmin", "Mshta",
			// Transform helpers
			"Base64Bash", "Base64BashC", "Base64Python",
			"Base64Perl", "Base64PowerShell", "HexBash",
			"CommentTrail", "BackgroundExec", "NohupExec",
			"SemicolonChain", "PipeChain",
			"URLEncodeStr", "DoubleURLEncodeStr",
		},
	},
	{
		path: "pkg/text",
		include: []string{
			"RandText", "RandAlpha", "RandAlphaNum", "RandNumeric",
			"RandHex", "RandBytes", "RandInt", "RandBool",
			"RandElement", "RandUserAgent",
		},
	},
	{
		path:    "pkg/c2/shell",
		include: []string{"New"},
		renames: map[string]string{"New": "NewListener"},
	},
}

func main() {
	pkgPaths := make([]string, len(specs))
	for i, spec := range specs {
		pkgPaths[i] = module + "/" + spec.path
	}

	cfg := &packages.Config{Mode: packages.NeedTypes | packages.NeedName}
	pkgs, err := packages.Load(cfg, pkgPaths...)
	if err != nil {
		fatal("loading packages: %v", err)
	}

	pkgMap := make(map[string]*packages.Package, len(pkgs))
	for _, pkg := range pkgs {
		pkgMap[pkg.PkgPath] = pkg
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	buf.WriteString(header)

	var imports []string
	for _, spec := range specs {
		full := module + "/" + spec.path
		if spec.alias != "" {
			imports = append(imports, fmt.Sprintf("\t%s %q", spec.alias, full))
		} else {
			imports = append(imports, fmt.Sprintf("\t%q", full))
		}
	}
	buf.WriteString("import (\n")
	for _, imp := range imports {
		buf.WriteString(imp + "\n")
	}
	buf.WriteString(")\n\n")

	for _, spec := range specs {
		full := module + "/" + spec.path
		pkg, ok := pkgMap[full]
		if !ok {
			fatal("package %s not loaded", full)
		}

		qualifier := pkg.Name
		if spec.alias != "" {
			qualifier = spec.alias
		}

		scope := pkg.Types.Scope()
		names := scope.Names()
		slices.Sort(names)

		selective := spec.include != nil

		var typeAliases, consts, vars []string

		for _, name := range names {
			if !isExported(name) {
				continue
			}
			if slices.Contains(spec.skip, name) {
				continue
			}
			if selective && !slices.Contains(spec.include, name) {
				continue
			}

			sdkName := name
			if r, ok := spec.renames[name]; ok {
				sdkName = r
			}

			obj := scope.Lookup(name)
			ref := fmt.Sprintf("%s.%s", qualifier, name)

			switch obj.(type) {
			case *types.TypeName:
				typeAliases = append(typeAliases, fmt.Sprintf("\t%s = %s", sdkName, ref))
			case *types.Const:
				consts = append(consts, fmt.Sprintf("\t%s = %s", sdkName, ref))
			case *types.Var, *types.Func:
				vars = append(vars, fmt.Sprintf("\t%s = %s", sdkName, ref))
			}
		}

		if len(typeAliases)+len(consts)+len(vars) == 0 {
			continue
		}

		buf.WriteString(fmt.Sprintf("// --- %s ---\n\n", spec.path))

		if len(typeAliases) > 0 {
			buf.WriteString("type (\n")
			for _, line := range typeAliases {
				buf.WriteString(line + "\n")
			}
			buf.WriteString(")\n\n")
		}

		if len(consts) > 0 {
			buf.WriteString("const (\n")
			for _, line := range consts {
				buf.WriteString(line + "\n")
			}
			buf.WriteString(")\n\n")
		}

		if len(vars) > 0 {
			buf.WriteString("var (\n")
			for _, line := range vars {
				buf.WriteString(line + "\n")
			}
			buf.WriteString(")\n\n")
		}
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "generated code:\n%s\n", buf.String())
		fatal("formatting: %v", err)
	}

	if err := os.WriteFile("sdk.go", formatted, 0o644); err != nil {
		fatal("writing sdk.go: %v", err)
	}
	fmt.Println("sdk.go generated")
}

func isExported(name string) bool {
	return len(name) > 0 && name[0] >= 'A' && name[0] <= 'Z'
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "sdkgen: "+format+"\n", args...)
	os.Exit(1)
}

const header = `// Package sdk is the public facade for Pik module development.
// It re-exports types and functions from internal packages so that
// module authors only need a single import.
//
// Internal framework packages (pkg/runner, pkg/console, etc.) import
// pkg/core directly to avoid import cycles.
package sdk

`
