// Code generated by go generate; DO NOT EDIT.

// Package sdk is the public facade for Pik module development.
// It re-exports types and functions from internal packages so that
// module authors only need a single import.
//
// Internal framework packages (pkg/runner, pkg/console, etc.) import
// pkg/core directly to avoid import cycles.
package sdk

import (
	"github.com/Chocapikk/pik/pkg/c2/shell"
	"github.com/Chocapikk/pik/pkg/core"
	"github.com/Chocapikk/pik/pkg/log"
	"github.com/Chocapikk/pik/pkg/output"
	"github.com/Chocapikk/pik/pkg/payload"
	"github.com/Chocapikk/pik/pkg/text"
)

// --- pkg/core ---

type (
	AuthorRank     = core.AuthorRank
	CheckCode      = core.CheckCode
	CheckResult    = core.CheckResult
	Checker        = core.Checker
	CmdStager      = core.CmdStager
	Context        = core.Context
	Exploit        = core.Exploit
	Info           = core.Info
	Notes          = core.Notes
	Option         = core.Option
	OptionEnricher = core.OptionEnricher
	OptionType     = core.OptionType
	Params         = core.Params
	Pik            = core.Pik
	Query          = core.Query
	RefType        = core.RefType
	Reference      = core.Reference
	Reliability    = core.Reliability
	Request        = core.Request
	Response       = core.Response
	Stance         = core.Stance
	Target         = core.Target
	Values         = core.Values
)

const (
	AccountLockout    = core.AccountLockout
	Aggressive        = core.Aggressive
	ArtifactsOnDisk   = core.ArtifactsOnDisk
	Certain           = core.Certain
	CheckAppears      = core.CheckAppears
	CheckDetected     = core.CheckDetected
	CheckSafe         = core.CheckSafe
	CheckUnknown      = core.CheckUnknown
	CheckVulnerable   = core.CheckVulnerable
	ConfigChanges     = core.ConfigChanges
	CrashSafe         = core.CrashSafe
	CrashUnsafe       = core.CrashUnsafe
	Difficult         = core.Difficult
	IOCInLogs         = core.IOCInLogs
	Passive           = core.Passive
	RefCVE            = core.RefCVE
	RefEDB            = core.RefEDB
	RefGHSA           = core.RefGHSA
	RefPacketstorm    = core.RefPacketstorm
	RefURL            = core.RefURL
	RefVulnCheck      = core.RefVulnCheck
	Reliable          = core.Reliable
	RepeatableSession = core.RepeatableSession
	ServiceRestart    = core.ServiceRestart
	TypeAddress       = core.TypeAddress
	TypeBool          = core.TypeBool
	TypeEnum          = core.TypeEnum
	TypeInt           = core.TypeInt
	TypePath          = core.TypePath
	TypePort          = core.TypePort
	TypeString        = core.TypeString
	Typical           = core.Typical
	Unlikely          = core.Unlikely
	Unstable          = core.Unstable
	VeryReliable      = core.VeryReliable
)

var (
	CVE              = core.CVE
	CanCheck         = core.CanCheck
	Censys           = core.Censys
	CheckErr         = core.CheckErr
	CheckFail        = core.CheckFail
	CheckOK          = core.CheckOK
	Dedent           = core.Dedent
	EDB              = core.EDB
	Errorf           = core.Errorf
	FOFA             = core.FOFA
	GHSA             = core.GHSA
	Get              = core.Get
	Google           = core.Google
	HasOption        = core.HasOption
	Hunter           = core.Hunter
	LeakIX           = core.LeakIX
	List             = core.List
	NameOf           = core.NameOf
	Names            = core.Names
	NewContext       = core.NewContext
	NewParams        = core.NewParams
	OptAddress       = core.OptAddress
	OptBool          = core.OptBool
	OptEnum          = core.OptEnum
	OptInt           = core.OptInt
	OptPort          = core.OptPort
	OptRequired      = core.OptRequired
	OptString        = core.OptString
	OptTargetURI     = core.OptTargetURI
	Packetstorm      = core.Packetstorm
	Rankings         = core.Rankings
	RegisterEnricher = core.RegisterEnricher
	ResolveOptions   = core.ResolveOptions
	Shodan           = core.Shodan
	Sprintf          = core.Sprintf
	TargetLinux      = core.TargetLinux
	TargetWindows    = core.TargetWindows
	URL              = core.URL
	VulnCheck        = core.VulnCheck
	ZoomEye          = core.ZoomEye
)

// --- pkg/log ---

var (
	Debug   = log.Debug
	Error   = log.Error
	Status  = log.Status
	Success = log.Success
	Verbose = log.Verbose
	Warning = log.Warning
)

// --- pkg/output ---

var (
	Banner  = output.Banner
	Print   = output.Print
	Println = output.Println
	Spinner = output.Spinner
)

// --- pkg/payload ---

var (
	Awk                = payload.Awk
	BackgroundExec     = payload.BackgroundExec
	Base64Bash         = payload.Base64Bash
	Base64BashC        = payload.Base64BashC
	Base64Perl         = payload.Base64Perl
	Base64PowerShell   = payload.Base64PowerShell
	Base64Python       = payload.Base64Python
	Bash               = payload.Bash
	BashFD             = payload.BashFD
	BashMin            = payload.BashMin
	Bitsadmin          = payload.Bitsadmin
	Certutil           = payload.Certutil
	CommentTrail       = payload.CommentTrail
	Curl               = payload.Curl
	CurlPipe           = payload.CurlPipe
	DoubleURLEncodeStr = payload.DoubleURLEncodeStr
	HexBash            = payload.HexBash
	Java               = payload.Java
	Lua                = payload.Lua
	Mshta              = payload.Mshta
	Netcat             = payload.Netcat
	NetcatMkfifo       = payload.NetcatMkfifo
	NodeJS             = payload.NodeJS
	NohupExec          = payload.NohupExec
	PHP                = payload.PHP
	PHPDownload        = payload.PHPDownload
	Perl               = payload.Perl
	PerlDownload       = payload.PerlDownload
	PipeChain          = payload.PipeChain
	PowerShell         = payload.PowerShell
	PowerShellDownload = payload.PowerShellDownload
	PowerShellIEX      = payload.PowerShellIEX
	Python             = payload.Python
	PythonDownload     = payload.PythonDownload
	PythonPTY          = payload.PythonPTY
	Ruby               = payload.Ruby
	SemicolonChain     = payload.SemicolonChain
	Socat              = payload.Socat
	URLEncodeStr       = payload.URLEncodeStr
	Wget               = payload.Wget
	WgetPipe           = payload.WgetPipe
)

// --- pkg/text ---

var (
	RandAlpha     = text.RandAlpha
	RandAlphaNum  = text.RandAlphaNum
	RandBool      = text.RandBool
	RandBytes     = text.RandBytes
	RandElement   = text.RandElement
	RandHex       = text.RandHex
	RandInt       = text.RandInt
	RandNumeric   = text.RandNumeric
	RandText      = text.RandText
	RandUserAgent = text.RandUserAgent
)

// --- pkg/c2/shell ---

var (
	NewListener = shell.New
)
